/* This file should be replaced by element header generated by
 * gst-element-maker, or by your own source code.  To generate suitable
 * element header using gst-element-maker, run:
 *
 *   gst-element-maker  TODO BASE_CLASS
 *
 * Where BASE_CLASS is replaced by one of the base class templates,
 * such as basesrc, basetransform, audiofilter, videofilter2, etc.
 * Then copy the resulting gstTODO.h file over this file, and
 * gstTODO.c over gstTODO.c.
 */
/* The rest of this file is shim code to allow the project to compile */
#ifndef __GST_PLUGIN_TEMPLATE_H__
#define __GST_PLUGIN_TEMPLATE_H__

#include <gst/gst.h>
#include <gst/base/gstbasetransform.h>

G_BEGIN_DECLS

#define GST_TYPE_PLUGIN_TEMPLATE (gst_plugin_template_get_type())
G_DECLARE_FINAL_TYPE (GstPluginTemplate, gst_plugin_template,
    GST, PLUGIN_TEMPLATE, GstBaseTransform)

struct _GstPluginTemplate {
  GstBaseTransform element;

  gboolean silent;
};

G_END_DECLS

#endif /* __GST_PLUGIN_TEMPLATE_H__ */
